### ISSUE TITLE
Tools: self upgrade feature

### ISSUE THREAD

**Issue by young-s-park** [fortify/fcli#145]
Ability to upgrade fcli with a command. Check current version and if a newer version is available, download and replace the existing version.

**Comment by rsenden** [comment]
Not sure how easy it would be to implement this on all operating systems; some operating systems may not allow replacing the fcli executable with a new version while the executable is running. @young-s-park, can you explain how this is implemented for ScanCentral Client?

**Comment by young-s-park** [comment]
ScanCentral Client has a Launcher which handles the upgrades.

**Comment by rsenden** [comment]
Hi @young-s-park, although implemented differently than ScanCentral Client, this feature is now available, although realistically you'll need to run two commands:

* `fcli tool definitions update` to download and install the latest tool definitions bundle, listing all available tool versions
* `fcli tool fcli install -v latest --uninstall all` to install the latest fcli version and uninstall any previously installed versions

For example, suppose `latest` is defined as an alias for fcli version 3.0.0 in the tool definitions bundle, and you currently have fcli version 2.2.0 installed, the command above will:
* Install fcli 3.0.0 to `~/fortify/tools/fcli/3.0.0`
* Update wrapper scripts in generic `~/fortify/tools/bin` folder to point to the fcli 3.0.0 installation
* Delete `~/fortify/tools/fcli/2.2.0` (after user confirmation):
     * If not is use, delete immediately
     * If in use (which would usually be the case when upgrading an existing installation), mark for deletion; actual deletion will take place on the next fcli run.

Compared to using a launcher to perform an in-place upgrade, this approach has various advantages:
* Same approach for all tools that can be managed through fcli; FortifyVulnerabilityExporter, Debricked CLI, ScanCentral Client, ...
* Somewhat similar to the proven 'Windows update' approach, requiring an fcli restart to clean up files that are in use
* Clear directory structure, allowing users to easily see/verify what tool versions are currently installed
* Ability to have multiple versions of a tool installed, for example if they have a need to run an older version of a tool for some projects and use the latest version for all other projects. For example, they could run `fcli tool fcli install -v 2 --uninstall 2` to only upgrade fcli 2.x.y to the latest 2.x.y version, while keeping any existing 1.x.y and 3.x.y versions

Note that instead of relying on the postponed deletion of the tool versions to be uninstalled, users can of course also use a more manual approach:

* `fcli tool definitions update`
* `fcli tool fcli install -v latest` (note there's no `--uninstall` option)
* `fcli tool fcli uninstall -v 2.2.0,1` to uninstall all 1.x.y versions and version 2.2.0
