### ISSUE TITLE
fcli config lang list  command should list ALL supported languages

### ISSUE THREAD

**Issue by james-du1** [fortify/fcli#171]
fcli config lang list  command should list ALL supported languages, but only English returned

![image](https://user-images.githubusercontent.com/120057653/206317865-63eca45e-3ad9-4418-8333-b743e6ff1338.png)

**Comment by wtfacoconut** [comment]
Hey @james-du1.
Fcli does have the capability to present help information in multiple languages, but at the moment, we have only enabled English because we currently do not have full translations of fcli's help information in any other language.

This is one area of development that we are needing community help with as the  current fcli dev team, consists of people who only speak English, Dutch, and French.

**Comment by rsenden** [comment]
For now, we only support English and as such the `language` commands have been hidden.
