### ISSUE TITLE
GitHub Actions installer for fcli

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#199]
We need to add a GitHub actions installer like https://github.com/fortify/
[gha-setup-scancentral-client](https://github.com/fortify/gha-setup-scancentral-client)

**Comment by rsenden** [comment]
Subject to general discussions on our GitHub Actions, i.e. whether we keep the existing structure (separate repo per action), move all actions into a single repo (similar to Debricked), have actions based on use cases (like package->scan->report) instead of (or in addition to low-level setup-* actions, ...

**Comment by rsenden** [comment]
This functionality is already available through the https://github.com/fortify/github-action/tree/main/setup action, and will be further improved based on enhancements on `fcli tool` commands coming in fcli 2.2.0.
