### ISSUE TITLE
`fcli util ncd-report`: Recommendations for the ncd generated config

### ISSUE THREAD

**Issue by wtfacoconut** [fortify/fcli#297]
fcli version: `fcli version 0.20230505.122628-dev_2.0.0-beta, built on 2023-05-05 12:26:58`

I have some recommendations in regards to updates to the generated yaml config file:

1. For the `duplicateExpression` section, are the values `a1` and `a2` built-in variables or something? If so, then can we explicitly mention this in the comment? Otherwise, if they are meant to be a placeholder, then perhaps we can use a different placeholder name that's more obvious, like `JohnDoe1` and `JohnDoe2`.
2. Can we possibly use a different character than `#` as a prefix to `#env()` ? This is because `#` is the comment character in yaml, and the only reason why it's currently not being treated as a comment character in the config file is because of the `>` which treates the yaml attribute as a multi-line string. If a user ever puts `#env()` on the same line as the attribute, then it will be treated as a comment, which could easily cause some confusion when debugging. May I recomment the tilde `~` character as it doesn't appear to have any special meaning in yaml?
3. Lines 36, 75, 107, and 143 have an unnecessary new line after the `-` character. I'd comment removing the new line even though it would move up the comment that's one line below. One other reason for this is to keep the generated `report-config.yaml` file more consistent with the original config file, because `report-config.yaml` will remove the the new line anyways.
4. Something that I've noticed with the `report-config.yaml` file is that it will remove the double-quote character around strings that use them. If it's possible to preserve the double-quote characters, then please do so. If it's too much trouble to do that, then no worries, as it won't be the end of the world.
5. Line 142 has a small typo. It says "GitHub" when it should say "GitLab".
6. For the sections where the GitHub and GitLab API tokens are to be provided, maybe we can provide a link that a user can copy/paste into their browser. For GitHub (https://github.com/settings/tokens), and for GitLab (https://gitlab.com/-/profile/personal_access_tokens)
7. For the GitHub and GitLab API tokens, can we specify what minimum permissions are required?

**Comment by rsenden** [comment]
@wtfacoconut Thanks for the suggestions. Some feedback:

1. `a1` and `a2` in `duplicateExpression` are property names that I chose, with `a` for `author`. I wanted this to be short, so people configuring or looking at this expression can focus on the property names like `cleanName` that are used for actual matching, in particular because `a1` and `a2` may need to be repeated multiple times. Also, for consistency and to avoid potential issues, these should be in `camelCase` or all lowercase. So, potentially we could do something like `user1` or `jdoe1`, but I still think I like a 1-letter property name better, although we could choose a different letter like `u` for `user`. What do you think?
2. Preferably we should use `#` as this is what's used by default by SpEL, and it's consistent with function references in fcli query expressions for example.
3. I specifically formatted it this way because of the comments. I guess we could have something like this, although I think current approach is slightly clearer? Also, not sure what you mean with generated `report-config.yaml` removing the newline; the original config file is copied line by line, so should be identical to the original file.    
      ![image](https://user-images.githubusercontent.com/8635138/236777634-2689104a-832e-4c2d-9c2e-2a1cc61b982a.png)
4. Can you give an example? As stated above, the file is copied line-by-line and there should be no special interpretation/processing of any characters like double-quote characters.
5. Will fix that.
6. Good suggestion, will add the links in the comments.
7. Again good suggestion, although I'll need to check what minimum permissions are required. Do you happen to know?

**Comment by wtfacoconut** [comment]
Hey @rsenden , thanks for the reply. Here are my responses below:

1. I think that `a1` and `a2` work fine, especially if the expectation is that there could be many lines that repeat the usage of that property name. If the user has the ability to change that to something else, then maybe we can just mention this in the comments? 
2. Roger that and understood. No other comments from me.
3. On the issue of the "removed new line", please ignore that. I think my eyes must be playing tricks on me. Appologies and please ignore. Though, I do like the updated formatting that you're showing. It just looks really weird having a single "-" character sitting alone on a line.
4. Again like with # 3, please ignore and appologies.
5. No comment.
6. No comment.
7. I'll try to do some testing on GitLab token permissions, GitHub Classic Tokens, and GitHub Granular Permission Tokens for minimum permission requirements. I'll report back after that.

**Comment by rsenden** [comment]
Closed by 5e8657e
