### ISSUE TITLE
doc: some common options not showing as double hyphen (--)

### ISSUE THREAD

**Issue by young-s-park** [fortify/fcli#315]
Probably due to some auto formatting, some of the options under "Common Options" is showing as a single long hyphen instead of a double hyphen. E.g. --help or --env-prefix look like there is only a single hyphen

**Comment by wtfacoconut** [comment]
Hey @young-s-park, which version of fcli did you use? You can get this with the `fcli --version` command.

**Comment by rsenden** [comment]
Example: https://fortify.github.io/fcli/dev_develop/#_env_prefix

Looks like the Asciidoc used to generate this documentation (https://github.com/fortify/fcli/blob/cbac6e2e9b413277b09d243b43880cdd4953a593/doc-resources/asciidoc/versioned/index.adoc?plain=1#L77) has single dashes instead of double dashes for some of the options, so should be easy to fix.
