### ISSUE TITLE
Documentation link should link to latest version

### ISSUE THREAD

**Issue by etnoy** [fortify/fcli#322]
Currently, the link to the documentation "Usage: https://fortify.github.io/fcli" line in the README links to the docs page without a version. That might confuse a new user since the page is quite empty. Only if they click on the small version button in the top right can they get any documentation at all.

My suggestion is that we link to the latest version, in this case https://fortify.github.io/fcli/v1.2.5/

**Comment by wtfacoconut** [comment]
Hey @etnoy,
We dont directly link to the latest stable version because we anticipat what there will be multiple stable versions of fcli in the future where each stable version will have been tested against various versions of different Fortify products. This is somewhat similar to how we currently do documentation via the MicroFocus document portal. With the MicroFocus document portal, you first select the product that you want, then you are presented with a list of versions that you can possibly select. The one thing what we could potentially do a better job of thought, is to draw a user's attention to the top right corver of the documentation page where the user can select the version of fcli they want to get documentation for.

Are you able to recommend an alternative way to address this issue that  you're describing? If you feel that I'm misunderstood your issue, please call me out on it.

**Comment by etnoy** [comment]
You understood the issue well. On our main docs page we have the version selector very obviously in the middle, like this: https://www.microfocus.com/documentation/fortify-static-code/

Mmaybe something similar could be adapted here?

**Comment by rsenden** [comment]
I'll need to check whether my changes work as expected once the build and publishing have completed; if all works well, the documentation landing page should now list the available documentation versions.
