### ISSUE TITLE
Reconsider FoD command aliases

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#362]
Some FoD commands have aliases for which it is questionable whether they provide any benefit or will ever be used. In particular:

- `app` / `application`: We should either remove the `application` alias, or add the same alias to the SSC `app` command for consistency
- `release` / `app-rel`: I don't see anyone using `app-rel` as its meaning is unclear if you don't know what command this is an alias for; `release` is much more clear and natural, so I'd suggest removing the `app-rel` alias
- `microservice` / `app-ms`: Same as above. If we want to have something shorter for `microservice`, maybe just `ms` will do
- `lookup` / `lookup-items`: Any way we can come up with a name that more properly describes this 'entity'?
    - Although I think it's named like this in the REST API, I don't think this terminology is used anywhere in the FoD web UI, so can we maybe come up with a better name? 
    - Entity names are usually in singular form, but `lookup-items` is in plural form
    - In general, primary entity name (`lookup-items`) should be used as the command name; alternative/shorter names should be aliases
    - Also see #361 for some additional considerations

**Comment by kadraman** [comment]
I agree on the naming and thought the aliases were a bit clunky- I think we agree on "app", "release" and "microservice"?

`lookup-items` is a weird one because it is just a dumping ground for types that appear across various FoD operations. Its not really a user-level entity as you don't need to know it exists if using the UI. In theory we shouldn't need to expose it as the individual commands should be able to refer to its types/vales as individual options as some do. However we don't have complete API coverage and allow users to do simple `fod rest` call in which case they might want to refer to its values - and hence why its probably good to keep it the same as exposed via the API?

**Comment by rsenden** [comment]
Agree on `app`, `release` and `microservice`.

As for `lookup-items`, are you saying that this is only useful for the `fcli fod rest call` command, not any of the other `fcli fod <entity>` commands? In that case, what about moving this functionality to `fcli fod rest lookup <name>` or something similar?

**Comment by rsenden** [comment]
When removing command aliases, please make sure that these aliases are no longer being referenced in the resource bundles, both for these commands themselves, as in the descriptions of other commands/options. For example, the `fcli fod app update` command description refers to the `app-rel` and `app-ms` aliases:

![image](https://github.com/fortify/fcli/assets/8635138/b966986a-3001-493b-8fbc-8c9890bd4e8a)

**Comment by rsenden** [comment]
Also, please make sure that any option names referencing those entities only use the new, single entity name. For example, the `fcli fod user update` has an `--add-apps / --add-applications` option; we should probably only have `--add-apps` (same of course for `--remove-applications`, ...)

**Comment by rsenden** [comment]
Also, please make sure class names are consistent with entity names. For example, if we have `release` as the entity name, then the corresponding classes should be named `FoDReleaseCommands` and `FoDRelease*Command`.
