### ISSUE TITLE
Consistency: Avoid use of System.out, use OutputMixin instead

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#91]
Some commands that can't produce useful output currently just write a status message like 'DONE' to stdout. For consistency, all commands should use OutputMixin such that users can choose different output formats, even if it's just a fixed status message. Also, utility/helper classes should refrain from using System.out, to avoid intervening with command output.

**Comment by wtfacoconut** [comment]
Understood. 
I believe that the two major reasons why you're wanting this is because:
-  This standardized the output of our commands so that regardless of what command is used, the user will know what to expect.
- Standardizing in this way helps to avoid the issue of unexpected data being redirected/piped to files or other commands.

I'll just add in here though that I think in some circumstances, we should have an exception to the rule, provided we can ensure that what ever information is presented to the user doesn't get included with actual data what would get piped/redirected. As an example, we may wish to display download/upload status information when transfering files between fcli and SSC.

**Comment by rsenden** [comment]
TODO: Double-check that all commands now properly use the output framework and progress helper for outputting.

**Comment by rsenden** [comment]
Confirmed; search on `System.out` references shows that `System.out` is only used in generic output framework, progress helpers, and by non-standard commands like encrypt/decrypt.
